name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test_ui:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check if test files exist
        run: |
          echo "Listing files in testCases"
          ls -la testCases
      - name: Run Playwright tests (headless)
        run: npx playwright test --grep @UI
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-ui
          path: test-results
          retention-days: 30
